version: '3.8'
services:
  
  app:
    build:
        context: ./
        dockerfile: ./docker/Dockerfile
    volumes:
      - ./:/app
    environment:
      NODE_ENV: development
    command: npm run start
    ports:
      - "3000:3000"
    networks:
            - dev-network
  
networks: 
    dev-network:
        external: true