# .......Development Stage.......
FROM node:16-alpine
# Set the working directory in the container
WORKDIR /usr/src/app
COPY . /usr/src/app
RUN npm install
# Install project dependencies
# Install ts-node globally for running TypeScript code

